# Generated by Django 4.1.5 on 2023-01-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acc_register",
            old_name="admin_id",
            new_name="acc_id",
        ),
    ]
