# Generated by Django 4.1.5 on 2023-02-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="set_otp_time",
            field=models.DateTimeField(null=True),
        ),
    ]
