# Generated by Django 4.1.5 on 2023-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_user_set_otp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="set_otp_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
